// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShuttleProject.Models.Data.MonitoringSystem;

#nullable disable

namespace ShuttleProject.Migrations
{
    [DbContext(typeof(MonitoringSystemContext))]
    partial class MonitoringSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("Role", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("RoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("UserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("LoginProvider"), false);

                    b.ToTable("UserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("RoleId", "UserId"), false);

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("LoginProvider"), false);

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DriverID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<string>("LicenseNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("char(100)")
                        .IsFixedLength();

                    b.HasKey("DriverId")
                        .HasName("PK2");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("DriverId"), false);

                    b.ToTable("Drivers", "dbo");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PassengerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.HasKey("PassengerId")
                        .HasName("PK5");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("PassengerId"), false);

                    b.ToTable("Passengers", "dbo");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    b.Property<string>("EndPoint")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<string>("RouteName")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("StartPoint")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.HasKey("RouteId")
                        .HasName("PK3");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("RouteId"), false);

                    b.ToTable("Routes", "dbo");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Shuttle", b =>
                {
                    b.Property<string>("ShuttleId")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("ShuttleID");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("DriverID");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.HasKey("ShuttleId")
                        .HasName("PK1");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ShuttleId"), false);

                    b.HasIndex("DriverId");

                    b.ToTable("Shuttles", "dbo");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("DepartutreTime")
                        .HasColumnType("time");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("PassengerID");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    b.Property<string>("ShuttleId")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("ShuttleID");

                    b.Property<string>("TripStatus")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.HasKey("TripId")
                        .HasName("PK4");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("TripId"), false);

                    b.HasIndex("PassengerId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ShuttleId");

                    b.ToTable("Trips", "dbo");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Shuttle", b =>
                {
                    b.HasOne("ShuttleProject.Models.Data.MonitoringSystem.Driver", "Driver")
                        .WithMany("Shuttles")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("RefDrivers5");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Trip", b =>
                {
                    b.HasOne("ShuttleProject.Models.Data.MonitoringSystem.Passenger", "Passenger")
                        .WithMany("Trips")
                        .HasForeignKey("PassengerId")
                        .IsRequired()
                        .HasConstraintName("RefPassengers3");

                    b.HasOne("ShuttleProject.Models.Data.MonitoringSystem.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("RefRoutes2");

                    b.HasOne("ShuttleProject.Models.Data.MonitoringSystem.Shuttle", "Shuttle")
                        .WithMany("Trips")
                        .HasForeignKey("ShuttleId")
                        .HasConstraintName("RefShuttles1");

                    b.Navigation("Passenger");

                    b.Navigation("Route");

                    b.Navigation("Shuttle");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Driver", b =>
                {
                    b.Navigation("Shuttles");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Passenger", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Route", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("ShuttleProject.Models.Data.MonitoringSystem.Shuttle", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
